### ISSUE TITLE
Error extracting protoc for version 3.21.4 windows-x86_32

### ISSUE THREAD

**Issue by RajaPatnala** [os72/protoc-jar-maven-plugin#136]
Getting the below error in the JMeter GRPC Request when trying to listing the protos.

Caused by: java.io.FileNotFoundException: Unsupported platform: protoc-3.21.4-windows-x86_32.exe
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:223) ~[jmeter-grpc-request.jar:?]
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:184) ~[jmeter-grpc-request.jar:?]
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:68) ~[jmeter-grpc-request.jar:?]
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:55) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invokeBinary(ProtocInvoker.java:223) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invoke(ProtocInvoker.java:117) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.ClientList.getServiceResolver(ClientList.java:47) ~[jmeter-grpc-request.jar:?]
	... 38 more

Here is the full stack trace
=======================

2023-02-22 23:19:46,869 ERROR v.z.b.GRPCSamplerGui: Proto folder path is empty. Please select your proto folder
java.lang.RuntimeException: Unable to resolve service by invoking protoc
	at vn.zalopay.benchmark.core.ClientList.getServiceResolver(ClientList.java:55) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.GRPCSamplerGui.getProtoMethods(GRPCSamplerGui.java:353) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.GRPCSamplerGui.reloadProtoMethods(GRPCSamplerGui.java:343) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.GRPCSamplerGui.lambda$registerListGRPCMethods$0(GRPCSamplerGui.java:498) ~[jmeter-grpc-request.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6635) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6400) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2263) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]
Caused by: vn.zalopay.benchmark.exception.ProtocInvocationException: Unable to execute protoc binary
	at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invokeBinary(ProtocInvoker.java:227) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invoke(ProtocInvoker.java:117) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.ClientList.getServiceResolver(ClientList.java:47) ~[jmeter-grpc-request.jar:?]
	... 38 more
Caused by: java.io.FileNotFoundException: Unsupported platform: protoc-3.21.4-windows-x86_32.exe
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:223) ~[jmeter-grpc-request.jar:?]
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:184) ~[jmeter-grpc-request.jar:?]
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:68) ~[jmeter-grpc-request.jar:?]
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:55) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invokeBinary(ProtocInvoker.java:223) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.protobuf.ProtocInvoker.invoke(ProtocInvoker.java:117) ~[jmeter-grpc-request.jar:?]
	at vn.zalopay.benchmark.core.ClientList.getServiceResolver(ClientList.java:47) ~[jmeter-grpc-request.jar:?]
	... 38 more

**Comment by wisew** [comment]
I had the same problem,Did you solve the problem yet

**Comment by RajaPatnala** [comment]
Hi Yes, I started using the openJDK 1.7 and the issue disappeared.

**Comment by sdoeringNew** [comment]
I solved it by dismissing the ``protocVersion`` property in the plugin and start using the ``protocArtifact`` property.

    <protocArtifact>com.google.protobuf:protoc:${protobuf.version}</protocArtifact>
    

That seems to be a common issue. See:
    https://github.com/os72/protoc-jar-maven-plugin/issues/124
    https://github.com/os72/protoc-jar-maven-plugin/issues/131
