### ISSUE TITLE
NullPointerException when includeStdTypes is set to true

### ISSUE THREAD

**Issue by ToBeKedge** [os72/protoc-jar-maven-plugin#60]
Hi,

I just upgrade my project for protoc-3.5.1/protoc-jar-maven-plugin-3.5.1.1 to protoc-3.6.1/protoc-jar-maven-plugin-3.6.0.1 and I got this error during build:

>		[ERROR] Failed to execute goal com.github.os72:protoc-jar-maven-plugin:3.6.0.1:run (default) on project deepblue-connect-domain: Execution default of goal com.github.os72:protoc-jar-maven-plugin:3.6.0.1:run failed. NullPointerException -> [Help 1]
>		org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.os72:protoc-jar-maven-plugin:3.6.0.1:run (default) on project deepblue-connect-domain: Execution default of goal com.github.os72:protoc-jar-maven-plugin:3.6.0.1:run failed.
>				at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
>				at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
>				at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
>				at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
>				at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
>				at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
>				at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
>				at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
>				at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
>				at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
>				at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
>				at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
>				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>				at java.lang.reflect.Method.invoke(Method.java:498)
>				at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
>				at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
>				at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
>				at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
>		Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.github.os72:protoc-jar-maven-plugin:3.6.0.1:run failed.
>				at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
>				at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
>				... 19 more
>		Caused by: java.lang.NullPointerException
>				at com.github.os72.protocjar.Protoc.extractStdTypes(Protoc.java:378)
>				at com.github.os72.protocjar.maven.ProtocJarMojo.performProtoCompilation(ProtocJarMojo.java:388)
>				at com.github.os72.protocjar.maven.ProtocJarMojo.execute(ProtocJarMojo.java:327)
>				at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
>				... 20 more

But when I comment `<includeStdTypes>true</includeStdTypes>` in my configuration, build finish with success!

My working configuration:
>		<plugin>
>			<groupId>com.github.os72</groupId>
>			<artifactId>protoc-jar-maven-plugin</artifactId>
>			<version>${protoc-jar-maven-plugin.version}</version>
>			<executions>
>				<execution>
>					<phase>generate-sources</phase>
>					<goals>
>						<goal>run</goal>
>					</goals>
>					<configuration>
>						<protocArtifact>com.google.protobuf:protoc:${protobuf.version}:exe:windows-x86_64</protocArtifact>
>						
>						<includeDirectories>
>							<include>${project.basedir}/build/include/</include>
>						</includeDirectories>
>						<inputDirectories>
>							<include>${mercurial.proto.sources.dir}/public/include/proto/</include>
>						</inputDirectories>
>						<outputDirectory>src/main/java</outputDirectory>
>					</configuration>
>				</execution>
>			</executions>
>		</plugin>

Do you know this problem?

**Comment by os72** [comment]
Could be a regression caused by feature `includeMavenTypes` released for issue #19. Need to look

**Comment by bmhm** [comment]
@os72 @ToBeKedge 
 as I found out in https://github.com/os72/protoc-jar-maven-plugin/issues/61 it will work if you additionally set `<protocVersion>…` in root of the `<configuration />` element.

**Comment by os72** [comment]
Yes correct, thanks

Furthermore, there is no need to specify the platform, the plugin takes care of that:
`<protocArtifact>com.google.protobuf:protoc:${protobuf.version}</protocArtifact>`

But in most cases it's easier to specify protocVersion:
`<protocVersion>${protobuf.version}</protocVersion>`

Have a look also at using `includeMavenTypes` vs `includeStdTypes `

**Comment by bmhm** [comment]
If I only specify the protoc version, it will get stuck downloading the binary directly from central.

This behaviour is odd, suprising and not (well) documented.

**Comment by bmhm** [comment]
Your documentation does not state when to use std or maven types:
http://os72.github.io/protoc-jar-maven-plugin/run-mojo.html

It will only tell the technical difference.

You should merge #61 into this issue.

Also the above docs do not state that with protocArtifact maven is used for download, but with protocVersion a direct download will be attempted.

The main readme and a FAQ page in this wiki should clarify this both.

**Comment by os72** [comment]
Yes there is room for improvement :)

**Comment by victzh** [comment]
This happens again in slightly different circumstances: if .proto files needs to be recompiled, but actual content did not changed, the plug-in can't see ${protobuf.version} variable, so if you specify protocVersion explicitly, like 3.9.0 - it works, otherwise throws NullPointerException. Plugin version used 3.8.0
